config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, controllers: { registrations: 'registrations' },
                     path: '', path_names: { sign_in: ENV['LOGIN_PATH'] }

  root to: 'pages#home'
  get 'contact', to: 'contact_forms#new'
  resources :contact_forms, only: %i[create]
  resources :photos, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attributes :name,  validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message, validate: true

  def headers
    {
      subject: 'My Contact Form',
      to: ENV['DELIVER_TO_EMAIL'],
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.deliver
      redirect_to root_path
      flash[:success] = "Your email has been sent! 😀"
    else
      render :new
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @photos = Photo.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to root_path
      flash[:success] = "Photo with title \"#{@photo.title}\" succesfully created! 😁"
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/contact_forms/new.html.erb
<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KdPhotos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/photos/new.html.erb
<%= simple_form_for @photo do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :image %>
  <%= f.input :image_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %> alert-dismissible fade show" role='alert'>
    <span><%= value %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class='navbar d-flex justify-content-between'>
  <div class='nav-left'>
    <%= link_to 'Home', root_path  %>
  </div>
  <div class='nav-right'>
    <% if user_signed_in? %>
      <%= link_to "New Photo", new_photo_path, class: 'btn btn-success' %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Contact', contact_path %>
      <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
  </div>
</div>